"""
set.lua parser — reads a Spring mapconfig/featureplacer/set.lua file and
returns a flat list of placements.

set.lua format (generated by FeaturePlacer):
    local setcfg = {
        unitlist     = { {name=..., x=..., z=..., rot=...}, ... },
        buildinglist = { {name=..., x=..., z=..., rot=...}, ... },
        objectlist   = { {name=..., x=..., z=..., rot=...}, ... },
    }
    return setcfg

Some variants also include `player` or team metadata we don't care about.
We flatten all three lists into one, tagging each placement with its source
category so later logic can filter if needed.
"""

from typing import List, Dict, Any
import lupa
from lupa import LuaRuntime


def _lua_table_to_list_of_dicts(tbl) -> List[Dict[str, Any]]:
    """Convert a 1-indexed Lua array of tables to a Python list of dicts."""
    if tbl is None:
        return []
    if lupa.lua_type(tbl) != 'table':
        return []
    out = []
    for k in sorted(tbl.keys()):
        if not isinstance(k, int):
            continue
        entry = tbl[k]
        if lupa.lua_type(entry) != 'table':
            continue
        d: Dict[str, Any] = {}
        for ek, ev in entry.items():
            # Keep primitives only; skip nested tables (not used here)
            if isinstance(ek, str) and isinstance(ev, (int, float, str, bool)):
                d[ek] = ev
        out.append(d)
    return out


def parse_set_lua(source: str) -> List[Dict[str, Any]]:
    """Parse a set.lua source string and return a list of feature placements.

    Each placement is a dict with at least: name, x, z, rot, category
    where category ∈ {'unit', 'building', 'object'}.
    """
    lua = LuaRuntime(unpack_returned_tuples=True)

    # Wrap source so `return setcfg` works at module level
    wrapped = f"return (function()\n{source}\nend)()"
    try:
        result = lua.execute(wrapped)
    except Exception as e:
        print(f"      [set.lua] Parse error: {e}")
        return []

    if lupa.lua_type(result) != 'table':
        # Some set.lua files use `return { unitlist=..., ... }` directly;
        # our wrapper should have captured that. If not, bail.
        print(f"      [set.lua] Unexpected return type: {type(result).__name__}")
        return []

    placements: List[Dict[str, Any]] = []

    for category, key in (('unit', 'unitlist'),
                           ('building', 'buildinglist'),
                           ('object', 'objectlist')):
        sublist = result[key] if key in result.keys() else None
        for entry in _lua_table_to_list_of_dicts(sublist):
            if 'name' not in entry:
                continue
            placements.append({
                'category': category,
                'name': str(entry['name']).lower(),
                'x': float(entry.get('x', 0)),
                'z': float(entry.get('z', 0)),
                'rot': float(entry.get('rot', 0)),
            })

    return placements


def parse_set_lua_file(path: str) -> List[Dict[str, Any]]:
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        return parse_set_lua(f.read())


if __name__ == "__main__":
    import sys
    from collections import Counter
    if len(sys.argv) < 2:
        print("Usage: python set_lua_parser.py <set.lua>")
        sys.exit(1)
    placements = parse_set_lua_file(sys.argv[1])
    print(f"Loaded {len(placements)} placements")
    cats = Counter(p['category'] for p in placements)
    print(f"  By category: {dict(cats)}")
    names = Counter(p['name'] for p in placements)
    print(f"  Unique names: {len(names)}")
    print(f"  Top 10 most-placed:")
    for name, count in names.most_common(10):
        print(f"    {count:4d}  {name}")
